# Generated by Django 2.2.16 on 2022-05-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_genretitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenreTitle',
        ),
    ]
